### ISSUE TITLE
Modifying query params ends Shiny session

### ISSUE THREAD

**Issue by piotrbajger** [Appsilon/shiny.router#64]
### Prerequisites

**Package version:** latest github version (0.1.1) with shiny 1.3.1
**System Details:** Windows 10
**Running platform:** clean R session, testing app in Google chrome

### Description
Modifying query params ends Shiny session.

Our use case is that user authentication is done with reactiveValues in Shiny session and all the info is lost when we use links with query params.

**Expected behavior:**
Going from **app_url/?foo=bar/#!/route** to **app_url/?foo=baz/#!/route** should not end Shiny session.

**Actual behavior:**
When changing query strings, e.g. going from **app_url/?foo=bar/#!/route** to **app_url/?foo=baz/#!/route** the Shiny session ends (see MWE below).

**Possible fix:**
We worked around this by modifying parse_url_path in R/pages.R to support query strings of the form **app_url/#!/route?foo=bar** and the session apperas to be maintained between router calls.

### Minimal example - steps to reproduce
MWE to reproduce hosted here: https://github.com/piotrbajger/query.mwe.

Run the app with RScript runapp.R, click on the links and inspect the console output to see that the session ends.

**Comment by dokato** [comment]
Thanks, @piotrbajger for a detailed report on this. It looks like the browsers by default refresh the website after changing the query parameters when they are before `!#`. Could you elaborate a little more why this behaviour would be better for your applications?
And since you mentioned that you modified the router code already I invite you to submit a PR, where we could discuss in more details about technicalities of that solution.

**Comment by piotrbajger** [comment]
Thanks @dokato for getting back to us on this, I submitted a PR.

As I was saying, our use case is that we require users to login to view the app and logins happen through the Shiny session variable. If we now use querystrings, the browser refreshes (as you've said), the session ends and the users are redirected back to the login page.

I updated the MWE from the opening post to illustrate this behaviour.
